### PR TITLE
Update Lapin

### PR DESCRIPTION
**Pull request by shekohex**
Update Lapin to 0.3

### CODE REVIEW

**Comment by shekohex** [comment]
oh, noway that gonna work this way, I surrender 🤦‍♂ 🚶

**Comment by keithnoguchi** [comment]
Thanks @shekohex!  I'll try it tonight.

**Comment by keithnoguchi** [comment]
Upgraded to 0.29.  I'll take care of the rest to catch up to 0.33.

**Comment by keithnoguchi** [comment]
Pushed 1.1.0, which is based on lapin 0.34, the latest.

https://crates.io/crates/async-mq

**Pull request closed without merging**
